package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"runtime"
	"strings"
	"sync"
	"time"

	"certificate"
	"config"
	"modules/amqpmodule"
)

const rxQueue = "cert_analysis_queue"
const rxRoutKey = "cert_analysis"
const sevendays = time.Duration(168 * time.Hour)

var broker *amqpmodule.Broker
var wg sync.WaitGroup

func failOnError(err error, msg string) {
	if err != nil {
		log.Fatalf("%s: %s", msg, err)
		panic(fmt.Sprintf("%s: %s", msg, err))
	}
}

func panicIf(err error) bool {
	if err != nil {
		log.Println(fmt.Sprintf("%s", err))
		return true
	}

	return false
}

func printIntro() {
	fmt.Println(`
	##################################
	#    Expiring Certs Analyzer     #
	##################################
	`)
}

func isMozilla(cert certificate.Certificate) bool {

	for _, s := range mozSites {

		if strings.Contains(cert.ScanTarget, s) {
			return true
		}

		for _, san := range cert.X509v3Extensions.SubjectAlternativeName {
			if strings.Contains(san, s) {
				return true
			}
		}
	}

	return false
}

func isExpiring(cert certificate.Certificate) bool {

	na, err := time.Parse("2006-01-02T15:04:05", cert.Validity.NotAfter)
	if err != nil {
		panicIf(err)
	} else {

		if na.Sub(time.Now()) < sevendays {
			return true
		}
	}

	return false
}

//worker is the main body of the goroutine that handles each received message.
func worker(msgs <-chan []byte) {

	forever := make(chan bool)
	defer wg.Done()

	for d := range msgs {

		stored := certificate.Certificate{}

		err := json.Unmarshal(d, &stored)
		panicIf(err)

		if err != nil {
			continue
		}

		if stored.CA {
			continue //we do not want to check CAs for wildcards
		}

		if isMozilla(stored) {

			valInfo, ok := stored.ValidationInfo["Mozilla"]

			if !ok {
				log.Println("Mozilla TrustStore info not found...")
				continue
			}

			if !valInfo.IsValid {
				//certificate is not trusted by the mozilla truststore
				log.Printf("%s, with subjectCN: %s , is an untrusted mozilla cert", stored.Hashes.SHA1, stored.Subject.CommonName)
				continue
			}

			//should add check for invalid (for any given reason ) certs
			if isExpiring(stored) {
				log.Printf("%s, with subjectCN: %s , is expiring in less than 7 days. Is CA: %t \n", stored.Hashes.SHA1, stored.Subject.CommonName, stored.CA)
				//TODO:Mozdef publishing code goes here.
			}
		}
	}

	<-forever
}

func main() {
	var (
		err error
	)

	printIntro()

	conf := config.AnalyzerConfig{}

	var cfgFile string
	flag.StringVar(&cfgFile, "c", "/etc/observer/analyzer.cfg", "Input file csv format")
	flag.Parse()

	_, err = os.Stat(cfgFile)
	failOnError(err, "Missing configuration file from '-c' or /etc/observer/retriever.cfg")

	conf, err = config.AnalyzerConfigLoad(cfgFile)
	if err != nil {
		conf = config.GetAnalyzerDefaults()
	}

	cores := runtime.NumCPU()
	runtime.GOMAXPROCS(cores * conf.General.GoRoutines)

	broker, err = amqpmodule.RegisterURL(conf.General.RabbitMQRelay)

	failOnError(err, "Failed to register RabbitMQ")

	msgs, err := broker.Consume(rxQueue, rxRoutKey)

	if err != nil {
		failOnError(err, "Failed to Consume from receiving queue")
	}

	for i := 0; i < cores; i++ {
		wg.Add(1)
		go worker(msgs)
	}

	wg.Wait()
}

var mozSites = [...]string{
	"123done.org",
	"1billionplusu.com",
	"1billionplusyou.com",
	"airmozilla.com",
	"airmozilla.org",
	"allizom.org",
	"anosrep.org",
	"appbazaar.org",
	"appdir.org",
	"appsbazaar.org",
	"arewecompatibleyet.com",
	"arewefunyet.com",
	"arewegrowingyet.com",
	"arewemobileyet.com",
	"arewesnappyyet.com",
	"awsbox.org",
	"b2gcrb.com",
	"b2gcrb.org",
	"backtotheweb.org",
	"badgekit.org",
	"bmoattachments.org",
	"boot2gecko.net",
	"boot2gecko.org",
	"brendaneich.com",
	"brendaneich.org",
	"browserid.org",
	"bugzilla.org",
	"bugzilla.org.uk",
	"buildyourownbrowser.com",
	"calendar-project.org",
	"camino-browser.de",
	"caminobrowser.jp",
	"chi-sol.org",
	"chicagosummeroflearning.com",
	"chicagosummeroflearning.net",
	"chicagosummeroflearning.org",
	"choose.eu",
	"choosefirefox.org",
	"chooseindependent.org",
	"communitysysadmins.com",
	"communitysysadmins.org",
	"der-firefox-3.de",
	"desafiofirefoxos.com.br",
	"desafiofirefoxos.net.br",
	"designchallenges.org",
	"detodosparatodos.co",
	"detodosparatodos.com",
	"detodosparatodos.net",
	"detodosparatodos.org",
	"dev.mo",
	"developerchallenges.org",
	"devmo.org",
	"dfirefox.de",
	"diadefirefox.es",
	"difundefirefox.com",
	"diresworb.org",
	"discovershiretoko.com",
	"discovershiretoko.jp",
	"discovershiretoko.net",
	"discovershiretoko.org",
	"doctorjs.org",
	"dotmoz.net",
	"dotmoz.org",
	"downloadmozillafirefox.com",
	"dribrednuht.net",
	"drjs.org",
	"drumbeat.org",
	"dzienfirefoksa.pl",
	"ecmascript-lang.org",
	"ecmascript.org",
	"es-lang.org",
	"extend-the-web.com",
	"extend-the-web.info",
	"extend-the-web.jp",
	"extend-the-web.net",
	"extend-the-web.org",
	"extendfirefox.com",
	"extendfirefox.net",
	"extendfirefox.org",
	"extendfirefox3.com",
	"extendtheweb.com",
	"extendtheweb.info",
	"extendtheweb.jp",
	"extendtheweb.net",
	"extendtheweb.org",
	"extendthunderbird.com",
	"eyedee.me",
	"falloflearning.com",
	"falloflearning.net",
	"falloflearning.org",
	"fashionmyfirefox.com",
	"fashionyourfirefox.com",
	"fashionyourfox.com",
	"fastestfirefox.com",
	"fastfirefox.com",
	"ffox.it",
	"ffox.me",
	"fightagainstboredom.com",
	"fightagainstboredom.org",
	"fiirefox.de",
	"firebuglite.com",
	"firebuglite.org",
	"fireffox.de",
	"firefo.de",
	"firefoox.de",
	"firefox-academic-center.com",
	"firefox-academic-center.org",
	"firefox-academic-centers.com",
	"firefox-academic-centers.org",
	"firefox-browse.de",
	"firefox-browser.at",
	"firefox-browser.be",
	"firefox-downloadportal.de",
	"firefox-erweiterungen.de",
	"firefox-internet-browser.at",
	"firefox-jetzt.de",
	"firefox-kommt.de",
	"firefox-mozilla.nl",
	"firefox-os.de",
	"firefox-os.net",
	"firefox-os.org",
	"firefox-portal.de",
	"firefox-update.com",
	"firefox-update.net",
	"firefox-update.org",
	"firefox.al",
	"firefox.asia",
	"firefox.be",
	"firefox.cn.com",
	"firefox.co.il",
	"firefox.com",
	"firefox.com.br",
	"firefox.com.pt",
	"firefox.com.ru",
	"firefox.de.com",
	"firefox.eu.com",
	"firefox.hu",
	"firefox.id",
	"firefox.ie",
	"firefox.jpn.com",
	"firefox.kr.com",
	"firefox.lc",
	"firefox.lt",
	"firefox.me",
	"firefox.me",
	"firefox.ms",
	"firefox.my",
	"firefox.name",
	"firefox.no.com",
	"firefox.org.il",
	"firefox.org.uk",
	"firefox.pt",
	"firefox.qa",
	"firefox.ru.com",
	"firefox.se.com",
	"firefox.sk",
	"firefox.us.com",
	"firefox.web.com",
	"firefox.xxx-block",
	"firefox1.de",
	"firefox10.org",
	"firefox2download.de",
	"firefox2party.com",
	"firefox3party.com",
	"firefox4.org",
	"firefox4all.com",
	"firefox4all.org",
	"firefox9.org",
	"firefoxacademiccenter.com",
	"firefoxacademiccenter.org",
	"firefoxacademiccenters.com",
	"firefoxacademiccenters.org",
	"firefoxaddons.com",
	"firefoxbrand.com",
	"firefoxbrand.org",
	"firefoxbranding.com",
	"firefoxbranding.org",
	"firefoxbrowser.com",
	"firefoxbrowser.de",
	"firefoxbrowser.org",
	"firefoxc.de",
	"firefoxccstudio.org",
	"firefoxco.com",
	"firefoxco.org",
	"firefoxcompany.com",
	"firefoxcompany.net",
	"firefoxcompany.org",
	"firefoxcorp.net",
	"firefoxcorp.org",
	"firefoxcorporation.com",
	"firefoxcorporation.net",
	"firefoxcorporation.org",
	"firefoxcup.com",
	"firefoxcup2010.com",
	"firefoxd.de",
	"firefoxday.net",
	"firefoxday.org",
	"firefoxfestival.com",
	"firefoxfestival.org",
	"firefoxflicks.asia",
	"firefoxflicks.com",
	"firefoxflicks.es",
	"firefoxflicks.org",
	"firefoxformobile.com",
	"firefoxformobile.com",
	"firefoxgarden.com",
	"firefoxgarden.org",
	"firefoxgear.com",
	"firefoxhello.com",
	"firefoxhungary.hu",
	"firefoxik.ru",
	"firefoxlive.com",
	"firefoxlive.com",
	"firefoxlive.info",
	"firefoxlive.info",
	"firefoxlive.net",
	"firefoxlive.net",
	"firefoxlive.org",
	"firefoxlive.org",
	"firefoxmarkeplace.org",
	"firefoxmarketplace.mobi",
	"firefoxmarketplace.org",
	"firefoxmozilla.de",
	"firefoxmozilla.net",
	"firefoxnote.jp",
	"firefoxos.al",
	"firefoxos.at",
	"firefoxos.com",
	"firefoxos.de",
	"firefoxos.guru",
	"firefoxosappchallenge.com",
	"firefoxosappchallenge.org",
	"firefoxosappschallenge.com",
	"firefoxosappschallenge.org",
	"firefoxosbrand.com",
	"firefoxosbrand.org",
	"firefoxosbranding.com",
	"firefoxosbranding.org",
	"firefoxoshungary.hu",
	"firefoxosmaster.com",
	"firefoxparty.com",
	"firefoxschool.com",
	"firefoxschool.net",
	"firefoxschool.org",
	"firefoxsoftware.com",
	"firefoxstore.org",
	"firefoxtweetmachine.com",
	"firefoxupdate.net",
	"firefoxupdate.org",
	"firefoxusercontent.com",
	"firefoxvictory.com",
	"firerfox.de",
	"firfox.de",
	"firox.de",
	"firrefox.de",
	"foxaddons.com",
	"foxaddons.net",
	"foxaddons.org",
	"foxkeh.asia",
	"foxkeh.com",
	"foxkeh.jp",
	"foxkeh.net",
	"foxkeh.org",
	"free-downloadmozila.com",
	"free-downloadmozila.com",
	"frefox.de",
	"funnyfox.net",
	"funnyfox.org",
	"fxaddons.com",
	"fxaddons.net",
	"fxaddons.org",
	"fxos-persona.org",
	"genopen.org",
	"getfenec.com",
	"getfenec.net",
	"getfenec.org",
	"getfennec.com",
	"getfennec.com",
	"getfennec.net",
	"getfennec.org",
	"getfirebug.com",
	"getfirebuglite.com",
	"getfirebuglite.org",
	"getfirefox.asia",
	"getfirefox.com",
	"getfirefox.jp",
	"getfirefox.me",
	"getfirefox.me",
	"getfirefox.org",
	"getfirfox.com",
	"getopenvideo.com",
	"getopenvideo.org",
	"getpersonas.com",
	"getthunderbird.com",
	"getthunderbird.jp",
	"gfirefox.de",
	"gombot.org",
	"gratis-firefox.de",
	"gumbot.org",
	"hackasaurus.org",
	"helpamofoout.org",
	"hive.nyc",
	"hiveberlin.org",
	"hivecha.org",
	"hivechicago.com",
	"hivechicago.org",
	"hivekc.org",
	"hivelearning.org",
	"hivelearningchicago.com",
	"hivelearningchicago.org",
	"hivelearningnetwork.com",
	"hivelearningnetwork.org",
	"hivelearningnetworks.org",
	"hivelearningnyc.com",
	"hivelearningnyc.org",
	"hivevan.org",
	"impactmozilla.com",
	"itisatrap.org",
	"itsourdata.org",
	"itsyourdata.org",
	"jamdays.com",
	"jamdays.org",
	"journee-firefox.org",
	"knightmozilla.com",
	"knightmozilla.org",
	"kostenlos-firefox-downloaden.de",
	"lcip.org",
	"learningfreedomandtheweb.org",
	"lightbeamdb.org",
	"lightning-project.org",
	"livetitles.com",
	"livingdocs.org",
	"lizardwrangler.com",
	"magicink.org",
	"magicinkacademy.com",
	"magicinkacademy.org",
	"magicinkclub.com",
	"magicinkclub.org",
	"magicinkguild.com",
	"magicinkguild.org",
	"makeopenvideo.com",
	"makeopenvideo.org",
	"maker.ly",
	"makes.org",
	"marketplacefirefox.biz",
	"marketplacefirefox.co",
	"marketplacefirefox.com",
	"marketplacefirefox.info",
	"marketplacefirefox.mobi",
	"marketplacefirefox.net",
	"marketplacefirefox.org",
	"masterfirefoxos.biz",
	"masterfirefoxos.com",
	"masterfirefoxos.net",
	"masterfirefoxos.org",
	"misterfirefoxos.com",
	"mitmachwoche.de",
	"mitmachwochen.de",
	"mmozilla.de",
	"mobilefirefox.com",
	"mocilla.de",
	"modzilla-firefox.de",
	"modzilla.fr",
	"modzillafirefox.de",
	"mofodev.net",
	"mofopriv.net",
	"mofoprivstaging.net",
	"mofoprod.net",
	"mofostaging.net",
	"moozilafirefox.com",
	"moozilla.de",
	"morzila.de",
	"morzilla.at",
	"morzilla.de",
	"morzillafirefox.de",
	"mosilla.de",
	"motizilla.com",
	"motzila.de",
	"moxilla.de",
	"moz.am",
	"moz.bg",
	"moz.camp",
	"mozaddons.com",
	"mozaddons.net",
	"mozaddons.org",
	"mozapp.me",
	"mozarilla-firefox.de",
	"mozaws.net",
	"mozcenter.com",
	"mozcenter.net",
	"mozcenter.org",
	"mozcentral.com",
	"mozcentral.net",
	"mozcentral.org",
	"mozco.com",
	"mozco.net",
	"mozco.org",
	"mozcompany.com",
	"mozcompany.net",
	"mozcompany.org",
	"mozcorp.com",
	"mozcorp.net",
	"mozcorp.org",
	"mozcorporation.com",
	"mozcorporation.net",
	"mozcorporation.org",
	"mozdc.com",
	"mozdc.net",
	"mozdc.org",
	"mozdevcenter.com",
	"mozdevcenter.net",
	"mozdevcenter.org",
	"mozdevcentral.com",
	"mozdevcentral.net",
	"mozdevcentral.org",
	"mozdeveloper.com",
	"mozdeveloper.net",
	"mozdeveloper.org",
	"mozdevelopers.com",
	"mozdevelopers.net",
	"mozdevelopers.org",
	"mozdevnet.com",
	"mozdevnet.net",
	"mozdevnet.org",
	"mozellia.com",
	"moziila.de",
	"moziilla.de",
	"mozila.de",
	"mozila.eu",
	"mozila.fr",
	"mozila.org",
	"mozilathunderbird.com",
	"mozill.com",
	"mozill.de",
	"mozilla-albania.org",
	"mozilla-antarctica.org",
	"mozilla-antartica.org",
	"mozilla-botswana.org",
	"mozilla-browser.de",
	"mozilla-community.org",
	"mozilla-costarica.org",
	"mozilla-cotedivoire.org",
	"mozilla-danmark.dk",
	"mozilla-esperanto.org",
	"mozilla-europa.de",
	"mozilla-europe.de",
	"mozilla-europe.me",
	"mozilla-europe.org",
	"mozilla-factory.org",
	"mozilla-fierfox.de",
	"mozilla-firefox.cnkeyword",
	"mozilla-firefox.nl",
	"mozilla-firfox.de",
	"mozilla-france.com",
	"mozilla-france.org",
	"mozilla-greece.org",
	"mozilla-hispano.com",
	"mozilla-hispano.org",
	"mozilla-japan.jp",
	"mozilla-japan.org",
	"mozilla-jordan.org",
	"mozilla-jp.me",
	"mozilla-mauritius.org",
	"mozilla-mexico.com",
	"mozilla-mexico.net",
	"mozilla-mexico.org",
	"mozilla-nepal.org",
	"mozilla-nigeria.org",
	"mozilla-nl.org",
	"mozilla-org.de",
	"mozilla-pakistan.org",
	"mozilla-portal.de",
	"mozilla-portal.org",
	"mozilla-projekt.de",
	"mozilla-radio.de",
	"mozilla-reps.org",
	"mozilla-russia.org",
	"mozilla-srbija.org",
	"mozilla-thunderbird.cnkeyword",
	"mozilla-uganda.org",
	"mozilla-update.com",
	"mozilla-update.net",
	"mozilla-update.org",
	"mozilla-uruguay.org",
	"mozilla-world.com",
	"mozilla-world.net",
	"mozilla-world.org",
	"mozilla-zimbabwe.org",
	"mozilla.al",
	"mozilla.asia",
	"mozilla.at",
	"mozilla.berlin",
	"mozilla.bg",
	"mozilla.ca",
	"mozilla.cnkeyword",
	"mozilla.cnwirelesskeyword",
	"mozilla.cnwirelesskeyword",
	"mozilla.co.il",
	"mozilla.com",
	"mozilla.com.eg",
	"mozilla.com.hk",
	"mozilla.com.ru",
	"mozilla.com.sg",
	"mozilla.cz",
	"mozilla.de",
	"mozilla.eu",
	"mozilla.fr",
	"mozilla.hk",
	"mozilla.hu",
	"mozilla.id",
	"mozilla.ie",
	"mozilla.it",
	"mozilla.jo",
	"mozilla.jp",
	"mozilla.lc",
	"mozilla.lk",
	"mozilla.lt",
	"mozilla.me",
	"mozilla.me",
	"mozilla.ms",
	"mozilla.my",
	"mozilla.net",
	"mozilla.ng",
	"mozilla.or.jp",
	"mozilla.org",
	"mozilla.org.mx",
	"mozilla.org.np",
	"mozilla.org.uk",
	"mozilla.pe",
	"mozilla.ph",
	"mozilla.pk",
	"mozilla.pt",
	"mozilla.qa",
	"mozilla.ro",
	"mozilla.rs",
	"mozilla.sg",
	"mozilla.tv",
	"mozilla.vn",
	"mozilla.xxx-block",
	"mozilla2.de",
	"mozilla24.com",
	"mozilla24.jp",
	"mozillaa.de",
	"mozillabd.org",
	"mozillacamp.org",
	"mozillacanada.org",
	"mozillacenter.com",
	"mozillacenter.net",
	"mozillacenter.org",
	"mozillacentral.com",
	"mozillacentral.net",
	"mozillacentral.org",
	"mozillacloud.com",
	"mozillacloud.org",
	"mozillaco.com",
	"mozillaco.net",
	"mozillaco.org",
	"mozillacolombia.org",
	"mozillacompany.com",
	"mozillacompany.net",
	"mozillacompany.org",
	"mozillacontributors.com",
	"mozillacorp.com",
	"mozillacorp.net",
	"mozillacorp.org",
	"mozillacorporation.com",
	"mozillacorporation.net",
	"mozillacorporation.org",
	"mozillacreativecollective.com",
	"mozillacreativecollective.org",
	"mozillactf.org",
	"mozillacup.com",
	"mozilladanmark.dk",
	"mozillademos.org",
	"mozilladev.com",
	"mozilladev.net",
	"mozilladev.org",
	"mozilladeveloper.com",
	"mozilladeveloper.net",
	"mozilladeveloper.org",
	"mozilladevelopercentral.com",
	"mozilladevelopercentral.net",
	"mozilladevelopercentral.org",
	"mozilladevelopers.com",
	"mozilladevelopers.net",
	"mozilladevelopers.org",
	"mozilladevs.com",
	"mozilladevs.net",
	"mozilladevs.org",
	"mozilladownload.de",
	"mozilladrumbeat.com",
	"mozilladrumbeat.com",
	"mozilladrumbeat.org",
	"mozillaecuador.org",
	"mozillaeurope.org",
	"mozillafactory.org",
	"mozillaferox.com",
	"mozillafestival.org",
	"mozillafirefox.com",
	"mozillafirefox.com.br",
	"mozillafirefox.in",
	"mozillafirefox.it",
	"mozillafirefoxdownload.de",
	"mozillafirefoxx.com",
	"mozillafirfox.de",
	"mozillafordevelopment.org",
	"mozillafoundation.com",
	"mozillafoundation.net",
	"mozillafoundation.org",
	"mozillahispano.org",
	"mozillaignite.com",
	"mozillaignite.org",
	"mozillaindia.org",
	"mozillalabs.com",
	"mozillalabs.net",
	"mozillalabs.org",
	"mozillamagazine.com",
	"mozillamarketplace.co",
	"mozillamarketplace.com",
	"mozillamarketplace.info",
	"mozillamarketplace.mobi",
	"mozillamarketplace.net",
	"mozillamedia.agency",
	"mozillamedia.biz",
	"mozillamedia.ca",
	"mozillamedia.cheap",
	"mozillamedia.club",
	"mozillamedia.co",
	"mozillamedia.co.uk",
	"mozillamedia.com",
	"mozillamedia.de",
	"mozillamedia.education",
	"mozillamedia.email",
	"mozillamedia.es",
	"mozillamedia.eu",
	"mozillamedia.in",
	"mozillamedia.info",
	"mozillamedia.io",
	"mozillamedia.me",
	"mozillamedia.mobi",
	"mozillamedia.net",
	"mozillamedia.org",
	"mozillamedia.pw",
	"mozillamedia.tv",
	"mozillamedia.uk",
	"mozillamedia.us",
	"mozillamedia.zone",
	"mozillamessaging.ch",
	"mozillamessaging.co.uk",
	"mozillamessaging.com",
	"mozillamessaging.cz",
	"mozillamessaging.de",
	"mozillamessaging.es",
	"mozillamessaging.fr",
	"mozillamessaging.it",
	"mozillamessaging.jp",
	"mozillamessaging.net",
	"mozillamessaging.org",
	"mozillamessaging.pl",
	"mozillamyanmar.org",
	"mozillanativo.org",
	"mozillaonline.com",
	"mozillaopennews.com",
	"mozillaopennews.org",
	"mozillapaladin.com",
	"mozillapaladin.org",
	"mozillapanama.org",
	"mozillaparty.com",
	"mozillapedia.com",
	"mozillapedia.net",
	"mozillapedia.org",
	"mozillaphilippines.org",
	"mozillapopcorn.com",
	"mozillapopcorn.org",
	"mozillaquebec.org",
	"mozillas.de",
	"mozillascience.com",
	"mozillascience.org",
	"mozillaservice.com",
	"mozillaservice.net",
	"mozillaservice.org",
	"mozillastore.com",
	"mozillasunbird.de",
	"mozillathimblelivepreview.net",
	"mozillaupdate.net",
	"mozillaupdate.org",
	"mozillauruguay.org",
	"mozillausa.org",
	"mozillausercontent.com",
	"mozillavenezuela.org",
	"mozillavoices.com",
	"mozillawebmaker.info",
	"mozillawebmakerproxy.net",
	"mozillaworld.com",
	"mozillaworld.net",
	"mozillaworld.org",
	"mozillazine.jp",
	"mozillian.net",
	"mozillian.org",
	"mozillians.com",
	"mozillians.net",
	"mozillians.org",
	"mozillion.net",
	"mozillion.org",
	"mozillions.com",
	"mozillions.net",
	"mozillions.org",
	"mozillla-firefox.de",
	"mozillla.de",
	"mozilllafirefox.de",
	"mozla.de",
	"mozlabs.com",
	"mozlabs.net",
	"mozlabs.org",
	"mozqa.com",
	"mozsecworld.org",
	"moztweet.com",
	"moztweet.com",
	"mozzilla-firefox.de",
	"mozzilla.com",
	"mozzilla.fr",
	"mozzillafirefox.de",
	"myfavoritebeer.org",
	"mywebmaker.org",
	"mzl.la",
	"native-persona.org",
	"neckoperf.net",
	"nextbiillionvoices.org",
	"nextbillionvoices.com",
	"nextbillionvoices.net",
	"nextbillionvoices.org",
	"nmozilla.de",
	"onebillionplusu.com",
	"onebillionplusyou.com",
	"onemozilla.org",
	"openattribute.com",
	"openbadger.com",
	"openbadger.org",
	"openbadges.org",
	"opendc.net",
	"opennews.com",
	"opennews.net",
	"opennews.org",
	"openstandard.com",
	"openstandard.org",
	"openstandard.tv",
	"opentochoice.com",
	"opentochoice.net",
	"opentochoice.org",
	"openvideo.tv",
	"openwebapps.com",
	"openwebapps.net",
	"openwebapps.org",
	"openwebcompatibility.com",
	"openwebcompatibility.org",
	"openwebday.com",
	"openwebday.org",
	"openwebdevice.org",
	"openwebdevicecompatibility.com",
	"openwebdevicecompatibility.org",
	"openweblibrary.com",
	"openweblibrary.org",
	"operationfirefox.com",
	"opstat.us",
	"owdcompatibility.com",
	"owdcompatibility.org",
	"owdcrb.com",
	"owdcrb.org",
	"owdcreviewboard.com",
	"owdcreviewboard.org",
	"owdreviewboard.com",
	"owdreviewboard.org",
	"pdfjs.com",
	"pdfjs.net",
	"pdfjs.org",
	"persona.org",
	"personaid.net",
	"personaid.org",
	"personas.id",
	"personatest.org",
	"personatestuser.org",
	"personausercontent.org",
	"pimpyourfirefox.com",
	"playfirefox.com",
	"playfirefox.net",
	"playfirefox.org",
	"popcornjs.com",
	"popcornjs.org",
	"priorartshare.com",
	"priorartshare.org",
	"privacyiconsproject.com",
	"privacyiconsproject.org",
	"privacypolici.es",
	"producefirefox.com",
	"publicsuffix.org",
	"quienestadetrasdefirefox.com",
	"quienestadetrasdefirefox.org",
	"raindrop.it",
	"refoxccstudio.org",
	"rekambew.org",
	"repo-the-web.org",
	"repotheweb.com",
	"repotheweb.org",
	"restmail.net",
	"rfirefox.de",
	"rnozilla.com",
	"rnozilla.net",
	"rnozilla.org",
	"rockyourfirefox.com",
	"school-of-firefox.com",
	"school-of-firefox.net",
	"school-of-firefox.org",
	"schooloffirefox.com",
	"schooloffirefox.net",
	"schooloffirefox.org",
	"schoolofwebcraft.org",
	"seamonkey-project.org",
	"seamonkey.de",
	"seamonkey.eu",
	"seamonkey.hu",
	"seamonkey.hu",
	"seamonkeyproject.org",
	"servo.org",
	"shapeoftheweb.com",
	"shapeoftheweb.org",
	"shumwayjs.net",
	"shumwayjs.org",
	"signupforthefuture.com",
	"sol-chi.com",
	"sol-chi.org",
	"spreadfennec.com",
	"spreadfennec.com",
	"spreadfirefox.asia",
	"spreadfirefox.com",
	"spreadfirefox.es",
	"spreadfirefox.jp",
	"spreadfirefox.me",
	"spreadmobilefirefox.com",
	"spreadseamonkey.com",
	"spreadthunderbird.com",
	"spreadthunderbird.org",
	"springoflearning.com",
	"springoflearning.net",
	"springoflearning.org",
	"standu.ps",
	"studiomofo.org",
	"summeroflearning.net",
	"summeroflearning.org",
	"sunbird-project.org",
	"supportfirefox.com",
	"switchtofirefox.com",
	"switchtothunderbird.com",
	"taskcluster.net",
	"testswarm.com",
	"theappbazaar.net",
	"theappbazaar.org",
	"theappsbazaar.com",
	"theappsbazaar.net",
	"theappsbazaar.org",
	"thefirefoxcup.com",
	"thefirefoxgarden.com",
	"thefirefoxgarden.org",
	"themozillian.com",
	"thenextbillion.org",
	"theopenstandard.net",
	"theopenstandard.org",
	"therepoweb.org",
	"thimbletest.org",
	"thunderbird-update.com",
	"thunderbird-update.net",
	"thunderbird-update.org",
	"thunderbird.asia",
	"thunderbird.cnkeyword",
	"thunderbird.com.br",
	"thunderbird.com.ru",
	"thunderbird.hu",
	"thunderbird.id",
	"thunderbird.net",
	"thunderbird.org.cn",
	"thunderbird.pt",
	"thunderbird.qa",
	"thunderbird.sk",
	"thunderbird.xxx-block",
	"thunderbirdupdate.com",
	"thunderbirdupdate.net",
	"thunderbirdupdate.org",
	"tinderbox.org",
	"tobmog.org",
	"togetherjs.com",
	"treeaj.com",
	"tweetzilla.org",
	"twizzilla.com",
	"twizzilla.com",
	"ukfirefox.com",
	"update-firefox.com",
	"updatefirefox.com",
	"updatefirefox.net",
	"updatefirefox.org",
	"updatemozilla.com",
	"updatemozilla.net",
	"updatemozilla.org",
	"updatethunderbird.com",
	"updatethunderbird.net",
	"updatethunderbird.org",
	"usfirefox.com",
	"usofirefox.org",
	"webactivities.org",
	"webfreedomfund.com",
	"webfreedomfund.org",
	"webfwd.net",
	"webfwd.org",
	"webifyme.org",
	"webmadecontent.org",
	"webmademovies.com",
	"webmademovies.org",
	"webmak.es",
	"webmaker.ninja",
	"webmaker.org",
	"webmakerconnect.org",
	"webmakerprototypes.org",
	"webofwonder.org",
	"webowonder.com",
	"webowonder.org",
	"webremixes.org",
	"webshaped.org",
	"welt-firefox-tag.de",
	"whenarewethere.org",
	"winteroflearning.com",
	"winteroflearning.net",
	"winteroflearning.org",
	"wip.bz",
	"wirelesskeyword.cn",
	"womoz.org",
	"worldfirefoxday.com",
	"worldfirefoxday.net",
	"worldfirefoxday.org",
	"www-firefox.at",
	"www-mozilla.at",
	"wwwmozilla.de",
	"xn--08jp3vya2q.jp",
	"xn--78j6dwa.jp",
	"xn--78j6dwa.jp",
	"xn--bckcfv4a1d8c5gd30b.jp",
	"xn--vckwa1a1a7o3bb.jp",
	"xn--yck6dwa.jp",
	"xn--yck6dwa2039e.jp",
	"xn--ycka9ezch8aze.jp",
	"xulapp.com",
	"xulapp.org",
	"xulplanet.jp",
	"yearoflearning.org",
	"youareells.com",
	"youareells.org",
}
