FROM golang:1.6
MAINTAINER Julien Vehent
ENV PROJECT=github.com/mozilla/tls-observatory

ADD . /go/src/$PROJECT

RUN mkdir /opt/cipherscan/
ADD cipherscan/ /opt/cipherscan/

RUN mkdir /etc/tls-observatory
ADD conf/ /etc/tls-observatory/

RUN groupadd -r tlsobs && useradd -r -g tlsobs tlsobs
USER tlsobs

RUN go install $PROJECT/tlsobs-scanner

ENTRYPOINT /go/bin/tlsobs-scanner
