FROM golang:1.7
MAINTAINER Julien Vehent
ENV PROJECT=github.com/mozilla/tls-observatory

ADD . /go/src/$PROJECT
RUN mv /go/src/$PROJECT/static /go/

RUN mkdir /etc/tls-observatory
ADD conf/ /etc/tls-observatory/

RUN groupadd -r tlsobs && useradd -r -g tlsobs tlsobs
USER tlsobs

RUN go install $PROJECT/tlsobs-api

# the API listening port
EXPOSE 8083

CMD /go/bin/tlsobs-api
