FROM golang:latest
MAINTAINER Julien Vehent
ENV PROJECT=github.com/mozilla/tls-observatory

ADD . /go/src/$PROJECT

RUN mkdir /etc/tls-observatory
ADD conf/ /etc/tls-observatory/

RUN groupadd -r tlsobs && useradd -r -g tlsobs tlsobs
USER tlsobs

RUN go install $PROJECT/tlsobs-runner

ENTRYPOINT /go/bin/tlsobs-runner
